spring.application.name=sistema-upa

# O banco será configurado durante a Sprint responsável pelo Neon.
# Quando chegar essa etapa, remover a exclusão abaixo e adicionar:
#
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}
# spring.jpa.hibernate.ddl-auto=update

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server.port=${PORT:8080}
