spring.application.name=sistema-upa

server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

app.frontend.url=${FRONTEND_URL:http://127.0.0.1:5500}
app.admin.email=${ADMIN_EMAIL:admin@upa.com}
app.admin.password=${ADMIN_PASSWORD:admin123}
